### ISSUE TITLE
push?

### ISSUE THREAD

**Issue by roymacdonald** [ofZach/dayForNightREFLECT#1]
Hey Zach, can you push the code for this, please?
All the best

**Comment by ofZach** [comment]
sorry I had a big file (test movie) so this didn't get pushed, hold on....

**Comment by ofZach** [comment]
done you may need this movie to compile this without a camera: 
(ie, not live) 

https://www.dropbox.com/s/d8r1dzgadx596ml/ScopeBox%20Movie-1-blah%20movie.mov?dl=0

**Comment by roymacdonald** [comment]
awesome! thanks.

**Comment by ofZach** [comment]
ps: some hack-y highlights as discussed in houston: 

embed the frame num in the fbo (so that I can know which frame num my readback corresponds to) 

https://github.com/ofZach/dayForNightREFLECT/blob/master/reflect/src/bounce/bounceManager.cpp#L197-L230

drawing the lines into an image using the index color in the array: 

https://github.com/ofZach/dayForNightREFLECT/blob/master/reflect/src/bounce/bounceManager.cpp#L199-L203

this part is the bouncing, which uses something like bresenham (I think this is more of a line fill algorithm) to walk along the line and check if it hits something

https://github.com/ofZach/dayForNightREFLECT/blob/master/reflect/src/bounce/bounceThread.cpp#L62-L91

there's alot of scale factors everywhere which make the code harder to read... I tried to optimize but then in the end, scaled up the fbo / line drawing technique to get better fidelity (and dropped the total number of lines animating, etc, adding some temporal smoothing, etc).

**Comment by roymacdonald** [comment]
great! all the ghetto hacks!
I didn't know that there was ofLineSegmentIntersection. super handy. :)
